### ISSUE TITLE
Wrong calculation of boundary for birdseye warped image

### ISSUE THREAD

**Issue by DataQub3** [sesstigit/Android-Car-duino#3]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
Currently the boundary of the birdseye warped image is blanked (after Canny edge detection) by a line 12 pixels wide.  Without blanking, the car will incorrectly follow the edge rather than the road.

The line does not need to be 12 pixels wide if the warped image boundary calculation is correct.

Blanking a large part of the image means image processing won't work so well.

* **Related code**
[BirdseyeTransformer.cpp](https://github.com/sesstigit/Android-Car-duino/blob/master/app/src/main/jni/Autodrive/src/imageprocessor/BirdseyeTransformer.cpp)
```
// Fudged calculation of border
left_image_border_ = linef(Autodrive::POINT(b_lines.left.begin.x - b_lines.left.end.x / 2 +5, b_lines.left.end.y), Autodrive::POINT(0, b_lines.left.begin.y));
    right_image_border_ = linef(Autodrive::POINT(b_lines.right.begin.x - (b_lines.right.end.x - im_width) / 2 +5, b_lines.right.end.y), Autodrive::POINT(im_width, b_lines.right.begin.y));
```

[ImageProcessor.cpp](https://github.com/sesstigit/Android-Car-duino/blob/master/app/src/main/jni/Autodrive/src/imageprocessor/ImageProcessor.cpp)
```
//! PAINT OVER BORDER ARTEFACTS FROM TRANSFORM in black (since canny always detects the border as a line)
//! BGR or RGBA does not matter here
birdseye_->left_image_border().draw(cannied_mat, cv::Scalar(0), img_conf_.transform_line_removal_threshold_);
birdseye_->right_image_border().draw(cannied_mat, cv::Scalar(0), img_conf_.transform_line_removal_threshold_);
```

* **What is the expected behavior?**
Blank the minimum amount of the warped image to get rid of the Canny edge along the border.

* **What is the motivation / use case for changing the behavior?**
Aim is to improve lane following.

* **Please tell us about your environment:**
  
  - Language:  C++, Visual Studio IDE, test_drive.cpp for testing

* **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links eg. stackoverflow)

**Comment by sesstigit** [comment]
The solution was simple in the end.  Start with the 4 corner points of the original image.  Then apply the birdseye warping to those points to find where they are in the warped image.  The resultant 4 points are the border of the warped image.
Used function perspectiveTransform(src, dst, birdseye_matrix) to transform the 4 points.

This method correctly found the border, so now black blanking of the border is applied only 2 pixels wide (could probably even just use 1 pixel width).
