### ISSUE TITLE
Add PID Controller for steering angle 

### ISSUE THREAD

**Issue by DataQub3** [sesstigit/Android-Car-duino#6]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**
The car does not always stay on the road.  It cannot cope with sharp bends, and it drifts to the edges of lanes.
Currently, the code calculates the steering angle based on the angle of the detected Lane lines, and adjusted by the car's offset from the centre of the lane.
However, there are many things that may be wrong with this approach.  Is the calculated Lane line angle correct, or is it affected by image warping or Birdseye view?   The detected Lane lines are sometimes in front of the car and sometimes alongside the car.  Turning angle should therefore be delayed sometimes, but it is not.  

* **Related code**

* **What is the expected behavior?**
The steering angle should steer the car smoothly around bends in the road.
Using something from control theory such as a PID Controller or an MPC Controller would ensure the steering angle is calculated properly to avoid overshoot.   

* **What is the motivation / use case for changing the behavior?** 
The code currently doesn't have a theoretical basis.  It just tries to see where to go and steers that way.  A PID controller will help by adding some rigour to the calculations.  

* **Please tell us about your environment:**
  - Version: 0.0.1
  - Language: [ C++ ]

* **Other information** (e.g. stacktraces, related issues, suggestions how to fix, links eg. stackoverflow)

**Comment by sesstigit** [comment]
PID.cpp and PID.h added for the PID controller.

Also added tuning parameters Kp (proportional gain), Kd (derivative gain), and Ki (integral gain).  These can be tuned from the Android app to ensure the car steers smoothly.

The PID controller aims to stay in the center of the lane.
