### ISSUE TITLE
Car is not responding to Bluetooth

### ISSUE THREAD

**Issue by ghost** [sesstigit/Android-Car-duino#8]
#### Issue description

The car is not responding to the CARdunio application. It doesn't not respond to commands, such as Auto Drive or Manual mode. 

#### Steps to reproduce the issue

Unknown. 

#### What's the expected result?

- Car should respond and move to CARdunio application. 

#### What's the actual result?

- Car does not move, the car does not appear to have received any commands. 

#### Additional details / screenshot

- TBA

**Comment by DataQub3** [comment]
Hmmm. That's no good.  Perhaps try some simple debugging first before we change the source code.
1) Is the car battery charged and on?  If so, there should be lights on the bluetooth module near the rear spoiler (but under the plastic body).  You may also hear some low humming from the servos.
2) Is the bluetooth connection working?  Are you using your own phone, or the phone that was already on the car?

I can update the App to indicate when the bluetooth connection is working (but I have no time until the weekend).

**Comment by ghost** [comment]
We've got a video of it. We're using the phone that came with the car, the does turn on, and the servos have power, but aren't producing any sound.

https://drive.google.com/open?id=1gTiWE5wsgGLyRPXoDw2_KYNp6-yuz95u

**Comment by DataQub3** [comment]
Thanks for the video.  Two possible fixes are:
1) Recharge the car battery.  If it is almost flat, then the electronics will turn on, but there will not be enough power to turn the servos (for steering and accelerator).
2) Check the bluetooth connection.  On the front screen of Carduino, select bluetooth.  A list of available devices should appear.  I think you click on HC05 to connect to the car.  Unfortunately you don't get any confirmation .... sorry.

Try those two.  If they don't work, then I can take a look in person.

**Comment by ghost** [comment]
The problem has been resolved. Looks like someone knocked out one of the cables for the Bluetooth module.

**Comment by DataQub3** [comment]
Great debugging!  Glad you fixed it.
